### ISSUE TITLE
Startup mixin crash (living entity mixin)

### ISSUE THREAD

**Issue by border999** [Draconic-Inc/BrandonsCore#101]
[debug.log](https://github.com/Draconic-Inc/BrandonsCore/files/10717128/debug.log)
[latest.log](https://github.com/Draconic-Inc/BrandonsCore/files/10717129/latest.log)
[After Where the Logs Stop.txt](https://github.com/Draconic-Inc/BrandonsCore/files/10717186/After.Where.the.Logs.Stop.txt)

**Comment by brandon3055** [comment]
If your game crashed then there should also be a crash report in the '.minecraft/crash-reports' directory. This usually contains more useful infomation thenm the log alone.

**Comment by border999** [comment]
I have checked the crash report folder a few times as I repeatedly hit upon this issue. I'm thinking the crash is happening to early in startup to get logged or something. Let me go find the last line real quick

**Comment by border999** [comment]
"Process crashed with exit code 1"

**Comment by brandon3055** [comment]
Do you have DruidCraft installed? If so that will be the cause.

**Comment by border999** [comment]
yep, got that mod. Will report this over there and take Druidcraft out for the time being. Let me test to see if any other issues crop up.

**Comment by brandon3055** [comment]
Something to add toy your report.
The issue is we are both adding a 
```
LivingEntity getThis() {
    return (LivingEntity)this;
}
```
method in our LivingEntityMixin. But mine is public and theirs is private which is rewulting in a mixin conflict.
But I'm not sure which is actually 'correct' yet.

**Comment by border999** [comment]
https://github.com/MysticMods/Druidcraft/issues/150

**Comment by border999** [comment]
[crash-2023-02-12_18.35.25-client.txt](https://github.com/Draconic-Inc/BrandonsCore/files/10717613/crash-2023-02-12_18.35.25-client.txt)
for my own curiosity. Can you make heads or tails of this crash report I just got?

**Comment by brandon3055** [comment]
> [crash-2023-02-12_18.35.25-client.txt](https://github.com/Draconic-Inc/BrandonsCore/files/10717613/crash-2023-02-12_18.35.25-client.txt) for my own curiosity. Can you make heads or tails of this crash report I just got?

Ratehr hard to say for sure. But i *think* betterf3's DebugOptionMixin is adding something to the minecraft Options class that is truing to access a private field in the main Minecraft class resulting in a crash.

**Comment by brandon3055** [comment]
Found it! Its OptionsMixin from UnionLib.
Specifically this like right here.
https://github.com/Stereowalker/UnionLib/blob/1.18-forge/src/main/java/com/stereowalker/unionlib/mixin/client/OptionsMixin.java#L20

The odd thing is this line in their access transformer should ensure that crash does not happen. They are doing everything correctly as far as i can tell. But for some reason their access transformer must not have been applied.
https://github.com/Stereowalker/UnionLib/blob/1.18-forge/src/main/resources/META-INF/accesstransformer.cfg#L13

**Comment by brandon3055** [comment]
Ok, I am going to take the blame for this one. According to a friend of mine who is a mixin expert my method should be private. So I will fix this on my end. 

To be fair it was that same mixin expert that helped me figure out my mixins in the first place so the blame isn't *entirely* on me xD

**Comment by brandon3055** [comment]
Can you please confirm that these fix the issue?
[BrandonsCore-1.18.2-3.1.8.277-universal.jar](https://maven.covers1624.net/com/brandon3055/brandonscore/BrandonsCore/1.18.2-3.1.8.277/BrandonsCore-1.18.2-3.1.8.277-universal.jar)
[Draconic-Evolution-1.18.2-3.0.28.516-universal.jar](https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.18.2-3.0.28.516/Draconic-Evolution-1.18.2-3.0.28.516-universal.jar)

**Comment by border999** [comment]
fixed
