### ISSUE TITLE
[1.18] Crash with DruidCraft Regrowth (LivingEntityMixin)

### ISSUE THREAD

**Issue by Phweeeee** [Draconic-Inc/BrandonsCore#102]
When I used this in my modpack with Druidcraft Growth, I crashed. It was ONLY with this mod. no others in my pack. 

Latest: https://paste.gg/p/anonymous/f344bae385e9453bb4bddfb1e0d06fac

Debug: https://paste.gg/p/anonymous/3e1ba8929b094dd4958586ccb9e2e76e

**Comment by FoxMcloud5655** [comment]
I'd like to add that I'm pretty sure this is due to mixins.  Maybe something here is modifying the same thing; I'm not familiar enough to know.

**Comment by FoxMcloud5655** [comment]
Also, it seems like a bug report has already been filed here: #101

**Comment by brandon3055** [comment]
If your game crashed then there should also be a crash report in the '.minecraft/crash-reports' directory. This usually contains more useful infomation thenm the log alone.

**Comment by Phweeeee** [comment]
No crash report was generated from this crash.

**Comment by border999** [comment]
same here

**Comment by brandon3055** [comment]
https://github.com/Draconic-Inc/BrandonsCore/issues/101#issuecomment-1427243585

**Comment by brandon3055** [comment]
Can you please confirm that these fix the issue?
[BrandonsCore-1.18.2-3.1.8.277-universal.jar](https://maven.covers1624.net/com/brandon3055/brandonscore/BrandonsCore/1.18.2-3.1.8.277/BrandonsCore-1.18.2-3.1.8.277-universal.jar)
[Draconic-Evolution-1.18.2-3.0.28.516-universal.jar](https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.18.2-3.0.28.516/Draconic-Evolution-1.18.2-3.0.28.516-universal.jar)

**Comment by Phweeeee** [comment]
It does fix the issue.

**Comment by border999** [comment]
time to close issue then
