### ISSUE TITLE
Crash when entering the game

### ISSUE THREAD

**Issue by Dalassiu** [Draconic-Inc/BrandonsCore#114]
Help me please. I installed 1 more additional mod into the mod collection and now my game crashes when I try to log in. What to do?
Bug Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  RandomPatches (randompatches-1.12.2-1.21.0.3.jar)
  Particle Fixes (ParticleFixes-v1.0.2-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  Inventory Tweaks Coremod (inventorytweaks-1.64dev.151.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  BCModPlugin (backpacks1.12.2-3.5.8.jar)
  CreativePatchingLoader (creativecore_v1.10.25_mc1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/26/24 11:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.client.creativetab.DETab.<init>(Ljava/lang/String;Ljava/lang/String;I)V
	at net.foxmcloud.draconicadditions.client.creativetab.DATab.<init>(DATab.java:19)
	at net.foxmcloud.draconicadditions.DAFeatures.<clinit>(DAFeatures.java:33)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
	at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 407272944 bytes (388 MB) / 1073741824 bytes (1024 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_F6_pre1 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                 | Source                                             | Signature                                |
	|:----- |:------------------------ |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCH   | mcp                      | 9.42                    | minecraft.jar                                      | None                                     |
	| LCH   | FML                      | 8.0.99.99               | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                    | 14.23.5.2859            | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy        | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LCH   | randompatches            | 1.12.2-1.21.0.3         | randompatches-1.12.2-1.21.0.3.jar                  | None                                     |
	| LCH   | timetolive               | 0.1                     | 1.12.2-timetolive-0.1.jar                          | None                                     |
	| LCH   | bspkrscore               | 8.0.0                   | 1.12.2bspkrscore-universal-8.0.1.jar               | None                                     |
	| LCH   | damageindicatorsmod      | 1.0                     | [1.12.2]DamageIndicatorsMod-3.5.1.jar              | None                                     |
	| LCH   | treecapitator            | 1.43.0                  | [1.12]TreeCapitator-client-1.43.0.jar              | None                                     |
	| LCH   | codechickenlib           | 3.2.3.358               | codechickenlib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ancientwarfare           | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCH   | ancientwarfarestructure  | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCH   | ancientwarfarevehicle    | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCH   | ancientwarfarenpc        | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCH   | redstoneflux             | 2.1.1                   | redstoneflux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCH   | ancientwarfareautomation | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCH   | antiqueatlas             | 4.6.3                   | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
	| LCH   | antiqueatlasoverlay      | 1.2                     | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
	| LCH   | baubles                  | 1.5.2                   | baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | artifacts                | 1.12.2-1.2.1            | artifacts-1.12.2-1.2.1.jar                         | None                                     |
	| LCH   | atum                     | 2.0.17                  | atum-1.12.2-2.0.17.jar                             | None                                     |
	| LCH   | backpacks16840           | 3.5.8                   | backpacks1.12.2-3.5.8.jar                          | None                                     |
	| LCH   | battletowers             | 1.6.5                   | battletowers-1.12.2.jar                            | None                                     |
	| LCH   | bookshelf                | 2.3.590                 | bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | jei                      | 4.15.0.293              | jei_1.12.2-4.15.0.293.jar                          | None                                     |
	| LCH   | botania                  | r1.10-363               | Botania-r1.10-363.jar                              | None                                     |
	| LCE   | brandonscore             | 2.4.18                  | brandonscore-1.12.2-2.4.18.210-universal.jar       | None                                     |
	| LC    | cannibalism              | 5.6.5                   | cannibalism-5.6.5-1.12.2.jar                       | None                                     |
	| LC    | capsule                  | 1.12.2-3.3.11           | capsule-1.12.2-3.3.11.jar                          | None                                     |
	| LC    | cavern                   | 2.3.0                   | Cavern_1.12.2-v2.3.0.jar                           | None                                     |
	| LC    | chancecubes              | 1.12.2-5.0.2.345        | chancecubes-1.12.2-5.0.2.345.jar                   | None                                     |
	| LC    | chickens                 | 6.1.0                   | chickens-6.1.0.jar                                 | None                                     |
	| LC    | clockworkphase           | 1.0g                    | clockworkphase-1.12.2-1.0g.jar                     | None                                     |
	| LC    | cyclopscore              | 1.6.6                   | cyclopscore-1.12.2-1.6.6.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | colossalchests           | 1.7.3                   | colossalchests-1.12.2-1.7.3.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | combustfish              | 1.0.3.4                 | combustfish-1.12.2-1.0.3.4.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | creativecore             | 1.10.0                  | creativecore_v1.10.25_mc1.12.2.jar                 | None                                     |
	| LC    | razak_demonmod           | 1.0                     | Cursed+Mobs+-+1.12.2+-+2.2.jar                     | None                                     |
	| LC    | cxlibrary                | 1.6.1                   | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
	| LC    | cyberware                | 0.2.11.24               | cyberware-1.12.2-0.2.11.24.jar                     | None                                     |
	| LC    | cyclicmagic              | 1.20.2                  | cyclic-1.12.2-1.20.2.jar                           | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LC    | darkutils                | 1.8.230                 | darkutils-1.12.2-1.8.230.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | dimdoors                 | 1.12.2-3.1.2+UNOFFICIAL | dimensionaldoors-1.12.2-3.1.2.jar                  | None                                     |
	| LC    | divinerpg                | 1.6.4.1                 | DivineRPG-1.6.4.1.jar                              | None                                     |
	| LC    | doggytalents             | 1.15.1.5                | doggytalents-1.12.2-1.15.1.5.jar                   | None                                     |
	| LC    | dldungeonsjbg            | 1.13.2                  | doomlikedungeons-1.13.2-mc1.12.2.jar               | None                                     |
	| LC    | draconicevolution        | 2.3.25                  | draconic-evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
	| LC    | draconicadditions        | 1.17.0                  | Draconic-Additions-1.12.2-1.17.0.45-universal.jar  | None                                     |
	| LC    | durabilitynotifier       | 1.0.0                   | Durability+Notifier-1.0.0.jar                      | None                                     |
	| LC    | eleccore                 | 1.9.453                 | eleccore-1.12.2-1.9.453.jar                        | None                                     |
	| LC    | mcjtylib_ng              | 3.5.4                   | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LC    | elementaldimensions      | 0.4.0                   | elementaldimensions-1.12-0.4.0.jar                 | None                                     |
	| LC    | enchantability           | 1.1.1                   | enchantability-1.1.1.jar                           | None                                     |
	| LC    | eplus                    | 5.0.179                 | enchantingplus-1.12.2-5.0.179.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | tombstone                | 3.6.5                   | tombstone-3.6.5-1.12.2.jar                         | None                                     |
	| LC    | erebus                   | 1.0.31                  | Erebus-1.0.31.jar                                  | None                                     |
	| LC    | extrautils2              | 1.0                     | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | farlanders               | 1.0.1                   | farlanders-1.12.2-1.0.1.jar                        | None                                     |
	| LC    | gokistats                | 1.2.8                   | gokistats-1.2.8.jar                                | None                                     |
	| LC    | gottschcore              | 1.13.1                  | gottschcore-mc1.12.2-f14.23.5.2768-v1.13.1.jar     | None                                     |
	| LC    | hardcorerevival          | 1.2.0                   | hardcorerevival_1.12.2-1.2.0.jar                   | None                                     |
	| LC    | ichunutil                | 7.2.2                   | ichunutil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | hats                     | 7.1.1                   | hats-1.12.2-7.1.1.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | llibrary                 | 1.7.19                  | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire               | 1.9.1                   | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
	| LC    | infinitystorage          | @VERSION@               | InfinityStorage-1.4.jar                            | None                                     |
	| LC    | inventorytweaks          | 1.64+dev.151.822d839    | inventorytweaks-1.64dev.151.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LC    | journeymap               | 1.12.2-5.7.1            | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LC    | levelhearts              | 2.2.0                   | levelhearts-1.12.2-2.2.0.jar                       | None                                     |
	| LC    | libraryex                | 1.1.3                   | LibraryEx-1.12.2-1.1.3.jar                         | None                                     |
	| LC    | timecore                 | 1.0.1.1                 | TimeCore-1.12.2-1.0.1.1.jar                        | None                                     |
	| LC    | lootgames                | 1.0.3.1                 | LootGames-1.12.2-1.0.3.1.jar                       | None                                     |
	| LC    | mapfrontiers             | 1.12.2-1.5.1            | MapFrontiers-1.12.2-1.5.1.jar                      | None                                     |
	| LC    | som                      | 1.2.10-mc1.12.2         | MK1.12.2-1.2.11-beta.jar                           | None                                     |
	| LC    | mobscrops                | 2.2.0                   | mobscrops-1.12.2-2.2.0.jar                         | None                                     |
	| LC    | morefurnaces             | 1.10.5                  | morefurnaces-1.12.2-1.10.6.jar                     | None                                     |
	| LC    | morph                    | 7.2.0                   | morph-1.12.2-7.2.0.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | mowziesmobs              | 1.5.4                   | mowziesmobs-1.5.4.jar                              | None                                     |
	| LC    | naturescompass           | 1.8.5                   | naturescompass-1.12.2-1.8.5.jar                    | None                                     |
	| LC    | opframe                  | 1.4.0                   | onlinepicframe_v1.5.0-pre1_mc1.12.2.jar            | None                                     |
	| LC    | oreexcavation            | 1.4.150                 | oreexcavation-1.4.150.jar                          | None                                     |
	| LC    | overchanter              | 1.0.0.2                 | overchanter-1.0.0.2.jar                            | None                                     |
	| LC    | particlefixes            | 1.0.2                   | ParticleFixes-v1.0.2-1.12.2.jar                    | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LC    | pirates                  | 0.0.6                   | pirates-0.0.6b.jar                                 | None                                     |
	| LC    | randomenchantments       | @VERSION@               | randomenchants-0.1.5.jar                           | None                                     |
	| LC    | randomloot               | 1.7.3                   | randomloot1.7.4.jar                                | None                                     |
	| LC    | randomportals            | 1.12.2-1.8.1.1          | randomportals-1.12.2-1.8.1.1.jar                   | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LC    | reagenchant              | 1.1.1                   | Reagenchant-1.12.2-1.1.1.jar                       | None                                     |
	| LC    | xreliquary               | 1.12.2-1.3.4.796        | reliquary-1.12.2-1.3.4.796.jar                     | None                                     |
	| LC    | roguelike                | 2.1.3                   | roguelikedungeonsfnaredition-1.12.2-2.1.3.jar      | None                                     |
	| LC    | scp                      | 2.3.1                   | SCP+Lockdown-1.12.2-2.3.1-dev.jar                  | None                                     |
	| LC    | solarflux                | 12.3.8                  | solarfluxreborn_1.12.2-12.3.8.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LC    | soulshardsrespawn        | 1.12.2-1.1.1-13         | soulshardsrespawn-1.12.2-1.1.1-13.jar              | None                                     |
	| LC    | theoneprobe              | 1.4.28                  | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| LC    | thicctorch               | 1.0.0                   | Thicc+Torch+-+1.0.0+[Forge+1.12.2].jar             | None                                     |
	| LC    | tinymobfarm              | 1.0.5                   | tinymobfarm-1.12.2-1.0.5.jar                       | None                                     |
	| LC    | torcherino               | 7.6                     | torcherino-7.6.jar                                 | None                                     |
	| LC    | twilightforest           | 3.10.1013               | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
	| LC    | uniquee                  | 1.9.0                   | Unique+Enchantments+V1.12.2-1.9.jar                | None                                     |
	| LC    | veining                  | 1.3.2                   | veining-1.3.2-1.12.x.jar                           | None                                     |
	| LC    | waystones                | 4.1.0                   | waystones_1.12.2-4.1.0.jar                         | None                                     |
	| LC    | matteroverdrive          | 0.7.0.0                 | MatterOverdrive-1.12.2-0.7.1.0-universal.jar       | None                                     |
	| LC    | thebetweenlands          | 3.6.2                   | TheBetweenlands-3.6.2-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LC    | eleccoreloader           | 1.9.453                 | eleccore-1.12.2-1.9.453.jar                        | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
RandomPatches (randompatches-1.12.2-1.21.0.3.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Particle Fixes (ParticleFixes-v1.0.2-1.12.2.jar)
  com.fuzs.particlefixes.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Inventory Tweaks Coremod (inventorytweaks-1.64dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
BCModPlugin (backpacks1.12.2-3.5.8.jar)
  brad16840.core.ClassTransformer
CreativePatchingLoader (creativecore_v1.10.25_mc1.12.2.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.76' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F6_pre1
	OptiFine Build: 20191206-224929
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 551.76
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by FoxMcloud5655** [comment]
Please search issues when posting new ones.  This is not Brandon Core's fault, nor is it Draconic Additions' fault.

Update your mods.
