### ISSUE TITLE
Can't open Mob Grinder

### ISSUE THREAD

**Issue by Sly0511** [Draconic-Inc/BrandonsCore#96]
in build 3.0.14.247 I am unable to open ANY mob grinder
Here's some logs I don't know if they are relevant
https://paste.ee/p/blwPB

**Comment by FoxMcloud5655** [comment]
That version does not even exist.  Regardless, your crash report tells me you need to update Draconic Evolution, as your real version number is 3.0.22.444.  the latest version as of this post is 3.0.25.456.  You updated Brandon's Core without updating DE.
