### ISSUE TITLE
Draconic Evolution and Brandon's Core crash

### ISSUE THREAD

**Issue by Colt-Anderson** [Draconic-Inc/BrandonsCore#97]
I have no idea why. Crashes on startup of Minecraft. 1.16.5 Forge 36.2.34. Latest versions of both Mods.

latest.log: https://paste.ee/p/B1qtu
crash report: https://paste.ee/p/0Oy2a

**Comment by brandon3055** [comment]
It looks like the mod called "Too Fast" has broken mixins. And for some reason its just deciding to explode when i register my network. Which shouldn't even be remotely related to the mixin that is exploding.

**Comment by Colt-Anderson** [comment]
Interestingly I already removed that mod because it was causing problems during startup (during mixin injection). Even after removal, it is causing problems? I think my config is completely screwed up.
