### ISSUE TITLE
Incompatibility with Forestry and Modular Powersuits

### ISSUE THREAD

**Issue by Neposis** [Draconic-Inc/BrandonsCore#98]
With the addition of BrandonsCore, there are broken textures in Forestry backpacks/watering cans and the MPS 3D models.

**Comment by FoxMcloud5655** [comment]
Was this tested with those mods specifically?  What version of Forge were you running?  Which version of Brandon's Core?  Which version of Forestry or Modular Powersuits?  Can you upload the log file for the session in question that had these broken textures?

We've got to have more details if we want to help solve the problem!

**Comment by Neposis** [comment]
Heya,
it occurs with other mods as well so I'm thinking that it might have more to do with texture limits. I will reopen if it occurs again
